### ISSUE TITLE
Handle the svg tag <use>

### ISSUE THREAD

**Issue by pwicks86** [storborg/axibot#27]
Axibot should handle the svg tag <use>.

**Comment by storborg** [comment]
A way to generate this "in the wild" is by using the "clones" tool in Inkscape.

**Comment by pwicks86** [comment]
I've got a couple test svgs for this, is there a good place to put things like that in the project? 

Also, my first shot at handling this is:

- Whenever recurse_tree encounters a use tag, search the whole document for the referenced node (possibly caching the result)
- Clone the referenced node and apply whatever transformations are specified in the use tag and continue on

**Comment by storborg** [comment]
That seems reasonable, especially since searching a document tree for an ID is quite fast.

What are the possible values for ``xlink:href``? I think it's possible for that to contain both URLs or other file paths: do we want to support those, or just IDs in the same document?

**Comment by pwicks86** [comment]
> That seems reasonable, especially since searching a document tree for an ID is quite fast.

What's the idiomatic way to do this search in etree? The xpath expression that I would expect to work throws an exception...

**Comment by storborg** [comment]
What xpath expression are you trying? I think something like this should work:

``tree.find('//*[@id="element_id"]')``

**Comment by pwicks86** [comment]
PR for this is here: https://github.com/storborg/axibot/pull/32

**Comment by pwicks86** [comment]
Closed via pr
