### ISSUE TITLE
Polygon support

### ISSUE THREAD

**Issue by tkornack** [storborg/axibot#36]
In my design software (Sketch for macOS) certain shapes are output to SVG as `polygon`s. Any idea how hard it is to translate them to `path`s?

**Comment by storborg** [comment]
``polygon`` elements should be pretty easy to support, as well as ``polyline``.

As a temporary workaround, though, most vector editors have a 'coerce to path' feature of some kind. In Inkscape it's called "object to path", and I think Illustrator is similar. In Sketch it might be "convert to outlines"?

**Comment by storborg** [comment]
Added polygon and polyline support in 643db0bdc78374201ca922a0944f2e461fca38f0
