### ISSUE TITLE
Set maximum speed

### ISSUE THREAD

**Issue by tkornack** [storborg/axibot#38]
With my ballpoint pen, most curved lines plot nicely but long lines go too fast and are not well inked. Is there a way to set a maximum speed (perhaps for lengths greater than a few mm)?

**Comment by storborg** [comment]
Right now the only way to do that is by manually updating the ``SPEED_PEN_DOWN`` value in ``axibot.config``. #4 is the general ticket for better handling of updating config variables.

The values right now are more or less optimized for fine-tip roller ball pens, like the Pilot Precise V5 (0.5mm) or the Uniball Vision Stick Needle.

**Comment by storborg** [comment]
I'm closing this since it's kind of a dupe of #4.
