### ISSUE TITLE
USB ID String comparison failing due to case issues

### ISSUE THREAD

**Issue by digitalman2112** [storborg/axibot#41]
## Bug

The test for the USB ID string is case insensitive, and expects that the USB ID is uppercase. My AxiDraw string has lowercase letters and therefore the board is never found. Changing ebb.py to match my string 'USB VID:PID=04d8:fd92' allows the board to be found, and I can print with no issues.

## SVG File

This issue is NOT SVG dependent

## Your Environment

* Axibot version (git sha1 hash): latest, built from master
* Axidraw version (1,2 or 3): version 3
* Eibotboard version: (it is relatively new, I've not removed the cover to see the version)
* Operating System and version: Raspberry Pi Rasbian latest (fresh download)
* Python version: 2.7

**Comment by digitalman2112** [comment]
Note, EBB firmware version is 2.5.1

**Comment by pwicks86** [comment]
Should be fixed by 615f0143f89fab75b905a5786d762fade4aaa6cc

**Comment by digitalman2112** [comment]
Thanks for the quick fix!

**Comment by pwicks86** [comment]
Closing this.
